theme: jekyll-theme-minimal
logo: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flaticon.com%2Ffree-icon%2Fbioinformatics_6283247&psig=AOvVaw0elbualP-VhCfyHaP38wb1&ust=1710523986958000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCLCk0suk9IQDFQAAAAAdAAAAABBD
title: Bioinformatics Class (BIMM 143, Winter 2024)
